name = "Fabric of Joy"
author = "Haxtistic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af7450eeae086e25eaa5e4364f7a838c461fe0f2d1c39761c90f483e5fc5e263"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
