name = "Fabric of Joy"
author = "Haxtistic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45006d571265d2e9f3b66f26865c6cd45b2a5c7561c89b6e77a436acc9ee578d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
