name = "Fabric of Joy"
author = "Haxtistic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20bfdb79a65ebb627e430275dfa74a5e3f20502eb90323d882a842a026304abf"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
