name = "Fabric of Joy"
author = "Haxtistic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5701dd307444b8937ff91962f0b479437aaab9e747da61769f085dac0f1309ee"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
